#!/bin/bash

# Print
echo "
units           real
atom_style      full
dimension        3
boundary        p p p
" > combine.in
 
# Read both files parameters
nt=$(awk '/atom types/ {print '\$1'}' $1)
nb=$(awk '/bond types/ {print '\$1'}' $1)
na=$(awk '/angle types/ {print '\$1'}' $1)
nd=$(awk '/dihedral types/ {print '\$1'}' $1)
ni=$(awk '/improper types/ {print '\$1'}' $1)
nt2=$(awk '/atom types/ {print '\$1'}' $2)
nb2=$(awk '/bond types/ {print '\$1'}' $2)
na2=$(awk '/angle types/ {print '\$1'}' $2)
nd2=$(awk '/dihedral types/ {print '\$1'}' $2)
ni2=$(awk '/improper types/ {print '\$1'}' $2)
if [ ! -n "$ni" ]
then
 ni=0
fi
#Check if there are impropers or 0
if [ ! -n "$ni2" ]
then
 ni2=0
fi
nt3=$(($nt + $nt2))
nb3=$(($nb + $nb2))
na3=$(($na + $na2))
nd3=$(($nd + $nd2))
ni3=$(($ni + $ni2))

echo "
read_data    mof.lmps extra/bond/per/atom 100 extra/angle/per/atom 100 extra/dihedral/per/atom 100 extra/improper/per/atom 100 
read_data    pol.lmps add append offset $nt $nb $na $nd $ni 
" >> combine.in


echo " $nt3 $nb3 $na3 $nd3 $ni3"

# Print masses
grep -wns Masses $1 -A $(($nt+1)) | awk '{print $2}' > out
grep -wns Masses $2 -A $(($nt2+1)) | awk '{print $2}' >> out
sed -i '/^$/d' out
start=1
i=$start
while [[ $i -le $nt3 ]]
do
echo "mass $i" >> outn
    ((i = i + 1))
done
paste  outn out >> combine.in 
rm out*

# Print pairs
echo "
pair_style      lj/cut/coul/long 12.00
" >> combine.in
grep -wns Pair Coeffs $1 -A $(($nt+1)) | awk  '{$1="";print $0}' > out
sed -i '1,2d' out
grep -wns Pair Coeffs $2 -A $(($nt2+1)) | awk '{$1="";print $0}' > out2
sed -i '1,2d' out2
cat out out2 > out3
start=1
i=$start
while [[ $i -le $nt3 ]]
do
echo "pair_coeff $i $i" >> outn
    ((i = i + 1))
done
paste  outn out3 >> combine.in 
rm out*

echo "
pair_modify     tail yes mix arithmetic
kspace_style    pppm 0.000001
dielectric      1.0
special_bonds   lj/coul 0.0 0.0 0.5
" >> combine.in

# Print bonds
var1=$(grep -wns Bond Coeffs $1 | awk  '{$1=$2=$3="";print $0}')
var2=$(grep -wns Bond Coeffs $2 | awk  '{$1=$2=$3="";print $0}')
if [ "$var1" = "$var2" ]; then
echo "
bond_style     $var1
" >> combine.in
else
echo "
bond_style      hybrid $var1 $var2
" >> combine.in
fi
grep -wns Bond Coeffs $1 -A $(($nb+1)) | awk  '{$1="";print $0}' > out
sed -i '1,2d' out
grep -wns Bond Coeffs $2 -A $(($nb2+1)) | awk '{$1="";print $0}' > out2
sed -i '1,2d' out2
cat out out2 > out3
start=1
i=$start
while [[ $i -le $nb3 ]]
do
echo "bond_coeff $i" >> outn
    ((i = i + 1))
done
paste  outn out3 >> combine.in 
rm out*

# Print angles
var1=$(grep -wns Angle Coeffs $1 | awk  '{$1=$2=$3="";print $0}')
var2=$(grep -wns Angle Coeffs $2 | awk  '{$1=$2=$3="";print $0}')
if [ "$var1" = "$var2" ]; then
	echo "
angle_style     $var1
	" >> combine.in
	grep -wns Angle Coeffs $1 -A $(($na+1)) | awk  '{$1="";print $0}' > out
	grep -wns Angle Coeffs $2 -A $(($na2+1)) | awk '{$1="";print $0}' > out2
else 
	var3=$(grep -wns angle_style $3 | awk  '{print $2}')
	if [ "$var3" = "hybrid" ]; then
		var4=$(grep -wns angle_style $3 | awk  '{$1=$2="";print $0}')
		echo "
angle_style      hybrid $var4 $var2
		" >> combine.in
		grep -wns Angle Coeffs $4 -A $(($na+1)) | awk  '{$1=$2="";print $0}' > out
		grep -wns Angle Coeffs $2 -A $(($na2+1)) | awk '{$1="";print $0}' > out2
		start=-1
		i=$start
		while [[ $i -le $na2 ]]
		do
			echo "$var2" >> out3
			((i = i + 1))
		done
		paste out3 out2 > out4
		mv out4 out2
		rm out3
	else
		echo "
angle_style      hybrid $var1 $var2
		" >> combine.in
		grep -wns Angle Coeffs $4 -A $(($na+1)) | awk  '{$1=$2="";print $0}' > out
		grep -wns Angle Coeffs $2 -A $(($na2+1)) | awk '{$1="";print $0}' > out2
		start=-1
		i=$start
		while [[ $i -le $na ]]
		do
			echo "$var1" >> out3
			((i = i + 1))
		done
		paste out3 out > out4
		mv out4 out
		rm out3
		start=-1
		i=$start
		while [[ $i -le $na2 ]]
		do
			echo "$var2" >> out3
			((i = i + 1))
		done
		paste out3 out2 > out4
		mv out4 out2
		rm out3
	fi
fi
sed -i '1,2d' out
sed -i '1,2d' out2
cat out out2 > out3
start=1
i=$start
while [[ $i -le $na3 ]]
do
echo "angle_coeff $i" >> outn
    ((i = i + 1))
done
paste  outn out3 >> combine.in 
rm out*

# Print dihedral
var1=$(grep -wns Dihedral Coeffs $1 | awk  '{$1=$2=$3="";print $0}')
var2=$(grep -wns Dihedral Coeffs $2 | awk  '{$1=$2=$3="";print $0}')
if [ "$var1" = "$var2" ]; then
	echo "
dihedral_style     $var1
	" >> combine.in
	grep -wns Dihedral Coeffs $1 -A $(($nd+1)) | awk  '{$1="";print $0}' > out
	grep -wns Dihedral Coeffs $2 -A $(($nd2+1)) | awk '{$1="";print $0}' > out2
else 
	var3=$(grep -wns dihedral_style $3 | awk  '{print $2}')
	if [ "$var3" = "hybrid" ]; then
		var4=$(grep -wns dihedral_style $3 | awk  '{$1=$2="";print $0}')
		echo "
dihedral_style      hybrid $var4 $var2
		" >> combine.in
		grep -wns Dihedral Coeffs $4 -A $(($nd+1)) | awk  '{$1=$2="";print $0}' > out
		grep -wns Dihedral Coeffs $2 -A $(($nd2+1)) | awk '{$1="";print $0}' > out2
		start=-1
		i=$start
		while [[ $i -le $nd2 ]]
		do
			echo "$var2" >> out3
			((i = i + 1))
		done
		paste out3 out2 > out4
		mv out4 out2
		rm out3
	else
		echo "
dihedral_style      hybrid $var1 $var2
		" >> combine.in
		grep -wns Dihedral Coeffs $4 -A $(($nd+1)) | awk  '{$1=$2="";print $0}' > out
		grep -wns Dihedral Coeffs $2 -A $(($nd2+1)) | awk '{$1="";print $0}' > out2
		start=-1
		i=$start
		while [[ $i -le $nd ]]
		do
			echo "$var1" >> out3
			((i = i + 1))
		done
		paste out3 out > out4
		mv out4 out
		rm out3
		start=-1
		i=$start
		while [[ $i -le $nd2 ]]
		do
			echo "$var2" >> out3
			((i = i + 1))
		done
		paste out3 out2 > out4
		mv out4 out2
		rm out3
	fi
fi
sed -i '1,2d' out
sed -i '1,2d' out2
cat out out2 > out3
start=1
i=$start
while [[ $i -le $nd3 ]]
do
echo "dihedral_coeff $i" >> outn
    ((i = i + 1))
done
paste  outn out3 >> combine.in 
rm out*


# Print improper
var00=$(grep  "improper types" $1 | awk  '{print $1}')
var01=$(grep  "improper types" $2 | awk  '{print $1}')
if [ -n "$var00" ] && [ -n "$var01" ]; then
	var1=$(grep -wns Improper Coeffs $1 | awk  '{$1=$2=$3="";print $0}')
	var2=$(grep -wns Improper Coeffs $2 | awk  '{$1=$2=$3="";print $0}')
	if [ "$var1" = "$var2" ]; then
		echo "
improper_style     $var1
		" >> combine.in
		grep -wns Improper Coeffs $1 -A $(($ni+1)) | awk  '{$1="";print $0}' > out
		grep -wns Improper Coeffs $2 -A $(($ni2+1)) | awk '{$1="";print $0}' > out2
	else 
		var3=$(grep -wns improper_style $3 | awk  '{print $2}')
		if [ "$var3" = "hybrid" ]; then
			var4=$(grep -wns improper_style $3 | awk  '{$1=$2="";print $0}')
			echo "
improper_style      hybrid $var4 $var2
			" >> combine.in
			grep -wns Improper Coeffs $4 -A $(($ni+1)) | awk  '{$1=$2="";print $0}' > out
			grep -wns Improper Coeffs $2 -A $(($ni2+1)) | awk '{$1="";print $0}' > out2
			start=-1
			i=$start
			while [[ $i -le $ni2 ]]
			do
				echo "$var2" >> out3
				((i = i + 1))
			done
			paste out3 out2 > out4
			mv out4 out2
			rm out3
		else
			echo "
improper_style      hybrid $var3 $var2
			" >> combine.in
			grep -wns Improper Coeffs $4 -A $(($ni+1)) | awk  '{$1=$2="";print $0}' > out
			grep -wns Improper Coeffs $2 -A $(($ni2+1)) | awk '{$1="";print $0}' > out2
			start=-1
			i=$start
			while [[ $i -le $ni ]]
			do
				echo "$var3" >> out3
				((i = i + 1))
			done
			paste out3 out > out4
			mv out4 out
			rm out3
			start=-1
			i=$start
			while [[ $i -le $ni2 ]]
			do
				echo "$var2" >> out3
				((i = i + 1))
			done
			paste out3 out2 > out4
			mv out4 out2
			rm out3
		fi
	fi
	sed -i '1,2d' out
	sed -i '1,2d' out2
	cat out out2 > out3
elif [ -n "$var00" ]; then
	var3=$(grep -wns improper_style $3 | awk  '{print $2}')
	echo "
improper_style     $var3
	" >> combine.in
	grep -wns Improper Coeffs $4 -A $(($ni+1)) | awk  '{$1=$2="";print $0}' > out
	sed -i '1,2d' out
	mv out out3
elif [ -n "$var01" ]; then
	var2=$(grep -wns Improper $2 | awk  '{print $4}')
	echo "
improper_style     $var2
	" >> combine.in
	grep -wns Improper Coeffs $2 -A $(($ni2+1)) | awk  '{$1="";print $0}' > out
	sed -i '1,2d' out
	mv out out3
fi
if [ -z "$var00" ] && [ -z "$var01" ]; then
echo ""
else
start=1
i=$start
while [[ $i -le $ni3 ]]
do
echo "improper_coeff $i" >> outn
    ((i = i + 1))
done
paste  outn out3 >> combine.in 
rm out*
fi 

echo "
write_data combine.lmps" >> combine.in

# Modify lmp files 

cp $1 mof.lmps
cp $2 pol.lmps

num1=$(grep -n "zlo zhi" $1 | cut -f1 -d:)
num2=$(grep -n Atoms $1 | cut -f1 -d:)
num1=$(($num1+1))
num2=$(($num2-2))
sed -i "$num1","$num2"'{d;}' mof.lmps

sed -i "/atom types/s/$nt/$nt3/"  mof.lmps 
sed -i "/bond types/s/$nb/$nb3/"  mof.lmps 
sed -i "/angle types/s/$na/$na3/"  mof.lmps 
sed -i "/dihedral types/s/$nd/$nd3/"  mof.lmps 
if [ -n "$var00" ]; then
sed -i "/improper types/s/$ni/$ni3/"  mof.lmps 
else
if [ -n "$var01" ]; then
numb=$(grep -n "dihedral types" mof.lmps | cut -f1 -d:)
numb=$(($numb+1))
sed -i "${numb}s/.*/0 impropers\n${ni3} improper types\n/" mof.lmps
fi
fi

num1=$(grep -n "zlo zhi" $2 | cut -f1 -d:)
num2=$(grep -n Atoms $2 | cut -f1 -d:)
num1=$(($num1+1))
num2=$(($num2-2))
sed -i "$num1","$num2"'{d;}' pol.lmps

sed -i '/atom types/d' pol.lmps
sed -i '/bond types/d' pol.lmps
sed -i '/angle types/d' pol.lmps
sed -i '/dihedral types/d' pol.lmps
sed -i '/improper types/d' pol.lmps
